# Generated by Django 2.1 on 2018-08-09 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('address', models.TextField()),
                ('postnr', models.IntegerField()),
                ('by', models.TextField()),
                ('tlf', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('bank', models.TextField()),
                ('regnr', models.TextField()),
                ('kontonr', models.TextField()),
            ],
        ),
    ]
