# Generated by Django 2.1 on 2018-08-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('in', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_info',
            name='address',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='company_info',
            name='bank',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='company_info',
            name='by',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='company_info',
            name='kontonr',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='company_info',
            name='regnr',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='company_info',
            name='tlf',
            field=models.CharField(max_length=40),
        ),
    ]
