# Generated by Django 2.1 on 2018-08-10 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('in', '0002_auto_20180809_1416'),
    ]

    operations = [
        migrations.DeleteModel(
            name='company_info',
        ),
    ]
