# Generated by Django 2.1 on 2018-08-10 22:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('in', '0003_delete_company_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('address', models.TextField()),
                ('postnr', models.IntegerField()),
                ('by', models.TextField()),
                ('tlf', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('bank', models.TextField()),
                ('regnr', models.IntegerField()),
                ('kontonr', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
