# Generated by Django 2.1 on 2018-08-10 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('in', '0004_companyinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyinfo',
            name='created_date',
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='bank',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='by',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='kontonr',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='tlf',
            field=models.CharField(max_length=15),
        ),
    ]
