# Generated by Django 2.1 on 2018-08-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('in', '0005_auto_20180810_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
